src/Entity/MediaList.php
<?php

namespace App\Entity;

use App\Repository\MediaListRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MediaListRepository::class)]
class MediaList
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, unique: true)]
    private ?string $url = null;

    #[ORM\Column]
    private ?int $x_last_videos = null;

    #[ORM\Column]
    private ?int $delete_after = null;

    #[ORM\Column(length: 20)]
    private ?string $cronjob = null;

    #[ORM\Column]
    private ?int $quality = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $path = null;

    #[ORM\Column]
    private ?int $type = null;

    #[ORM\Column(type: 'boolean', options: ['default' => false])]
    private ?bool $archived = false;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $totalVideos = 0;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $downloadedVideos = 0;

    #[ORM\Column(options: ['default' => 0])]
    private ?int $deletedVideos = 0;

    #[ORM\Column(nullable: true)]
    private ?bool $lastUpdateResult = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): static
    {
        $this->url = $url;

        return $this;
    }

    public function getXLastVideos(): ?int
    {
        return $this->x_last_videos;
    }

    public function setXLastVideos(int $x_last_videos): static
    {
        $this->x_last_videos = $x_last_videos;

        return $this;
    }

    public function getDeleteAfter(): ?int
    {
        return $this->delete_after;
    }

    public function setDeleteAfter(int $delete_after): static
    {
        $this->delete_after = $delete_after;

        return $this;
    }

    public function getCronjob(): ?string
    {
        return $this->cronjob;
    }

    public function setCronjob(string $cronjob): static
    {
        $this->cronjob = $cronjob;

        return $this;
    }

    public function getQuality(): ?int
    {
        return $this->quality;
    }

    public function setQuality(int $quality): static
    {
        $this->quality = $quality;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): static
    {
        $this->path = $path;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function isArchived(): ?bool
    {
        return $this->archived;
    }

    public function setArchived(bool $archived): static
    {
        $this->archived = $archived;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getTotalVideos(): ?int
    {
        return $this->totalVideos;
    }

    public function setTotalVideos(?int $totalVideos): static
    {
        $this->totalVideos = $totalVideos;

        return $this;
    }

    public function getDownloadedVideos(): ?int
    {
        return $this->downloadedVideos;
    }

    public function setDownloadedVideos(?int $downloadedVideos): static
    {
        $this->downloadedVideos = $downloadedVideos;

        return $this;
    }

    public function getDeletedVideos(): ?int
    {
        return $this->deletedVideos;
    }

    public function setDeletedVideos(?int $deletedVideos): static
    {
        $this->deletedVideos = $deletedVideos;

        return $this;
    }

    public function isLastUpdateResult(): ?bool
    {
        return $this->lastUpdateResult;
    }

    public function setLastUpdateResult(?bool $lastUpdateResult): static
    {
        $this->lastUpdateResult = $lastUpdateResult;

        return $this;
    }
}

templates/add_mediaList.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une chaine ou une playlist{% endblock %}

{% block body %}
    <div class="form">
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.url) }}
            <div class="input-group">
                {{ form_widget(form.url) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.x_last_videos) }}
            <div class="input-group">
                {{ form_widget(form.x_last_videos) }}
            </div>
        </div>

        <div class="form-group">
            {{ form_label(form.delete_after) }}
            <div class="input-group">
                {{ form_widget(form.delete_after) }}
                <span class="input-text">jours (0 pour ne jamais supprimer)</span>
            </div>
            {{ form_errors(form.delete_after) }}
        </div>

        <div class="form-group">
            {{ form_label(form.cronjob) }}
            <div class="input-group">
                {{ form_widget(form.cronjob) }}
            </div>
            {{ form_errors(form.cronjob) }}
        </div>

        <div class="form-group">
            {{ form_label(form.quality) }}
            <div class="input-group">
                {{ form_widget(form.quality) }}
            </div>
            <span class="input-text" style="margin-top:.5em; font-style:italic; font-size:.75em">(Si qualité non disponible, qualité inférieure prise)</span>
            {{ form_errors(form.quality) }}
        </div>

        <div class="form-group">
            {{ form_label(form.path) }}
            <div class="input-group">
                {{ form_widget(form.path) }}
            </div>
            {{ form_errors(form.path) }}
        </div>
        <div class="form-group">
            <div class="input-group">
                <input type="submit" class="button add-button" value ="Ajouter" style="margin:auto">
            </div>
        </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{{ page_title | default('Pas de titre') }}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">
        <link href="{{ asset('css/styles.css') }}" rel="stylesheet" type="text/css" />
        <link rel="icon" type="image/png" href="{{ asset('favicon.gif') }}">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        <nav>
            <h1>Dorizonerr</h1>
            <ul>
                <li><a href="{{ path('index') }}">Home</a></li>
                <li><a href="{{ path('index.archived') }}">Archives</a></li>
                <li><a href="https://floriandorizon.fr" target="_blank">Dorizon Industries</a>&#8599;</li>
            </ul>
        </nav>
        <hr>
        <div class="wrapper">
            <div class="alert-container">
                {% for type, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="alert alert-{{ type }} flash-message">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
            {% block body %}{% endblock %}
        </div>
        <!--<canvas id="canvas">YOUR_TEXT</canvas>
        <canvas id="canvas2">YOUR_TEXT</canvas>
        <script src="{{ asset('js/matrix.js') }}"></script>-->
    </body>
</html>

templates/edit_mediaList.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EditMediaListController!{% endblock %}

{% block body %}
    <div class="form">
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.url) }}
            <div class="input-group">
                {{ form_widget(form.url) }}
            </div>
        </div>
        <div class="form-group">
            {{ form_label(form.x_last_videos) }}
            <div class="input-group">
                {{ form_widget(form.x_last_videos) }}
            </div>
        </div>

        <div class="form-group">
            {{ form_label(form.delete_after) }}
            <div class="input-group">
                {{ form_widget(form.delete_after) }}
                <span class="input-text">jours (0 pour ne jamais supprimer)</span>
            </div>
            {{ form_errors(form.delete_after) }}
        </div>

        <div class="form-group">
            {{ form_label(form.cronjob) }}
            <div class="input-group">
                {{ form_widget(form.cronjob) }}
            </div>
            {{ form_errors(form.cronjob) }}
        </div>

        <div class="form-group">
            {{ form_label(form.quality) }}
            <div class="input-group">
                {{ form_widget(form.quality) }}
            </div>
            <span class="input-text" style="margin-top:.5em; font-style:italic; font-size:.75em">(Si qualité non disponible, qualité inférieure prise)</span>
            {{ form_errors(form.quality) }}
        </div>

        <div class="form-group">
            {{ form_label(form.path) }}
            <div class="input-group">
                {{ form_widget(form.path) }}
            </div>
            {{ form_errors(form.path) }}
        </div>
        <div class="form-group">
            <div class="input-group">
                <input type="submit" class="button edit-button" value ="Modifier" style="margin:auto">
            </div>
        </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% if archive is defined %}
    {% set page_title %}
        Archive des playlists et des chaînes
    {% endset %}
{% else %}
    {% set page_title %}
        Index des playlists et des chaînes
    {% endset %}
{% endif %}

{% block title %} {{ page_title }} {% endblock %}

{% block body %}
    {% if archive is not defined %}
    <h3>Ajouter une chaine ou une playlist</h3>
    <a href="{{ path('add.mediaList') }}" class="button add-button">Ajouter</a>
    {% endif %}
    <hr>
    <h3>Playlists {{ archive is defined ? ' archivées' : '' }}</h3>
    <div class="table-container">
        <table>
            <colgroup>
                <col style="width: 4%;">
                <col style="width: 4%;">
                <col style="width: 30%;">
                <col style="width: 35%;">
                <col style="width: 15%;">
                <col style="width: 15%;">
            </colgroup>
            <thead>
            <tr>
                <th class="index-th-poster"></th>
                <th></th>
                <th>Nom</th>
                <th>URL</th>
                <th>Cronjob</th>
                <th>Age Max</th>
            </tr>
            </thead>
            <tbody>
            {% for playlist in playLists %}
            <tr>
                <td class="index-th-poster"><a href="{{ path('show.mediaList', {id: playlist.id}) }}" class="table-link">
                        <img src="{{ asset('downloaded/posters/' ~ playlist.title ~ '.jpg') }}"
                             onerror="this.onerror=null; this.src='{{ asset('downloaded/default-poster.jpg') }}';"
                             class="mediaList-poster"
                             style="max-width: 100px;"
                             alt="Poster de {{ playlist.title }}"/>
                    </a>
                </td>
                <td>
                    {% set healthClass = playlist.lastUpdateResult is same as(true)
                        ? 'good-health'
                        : (playlist.lastUpdateResult is same as(false) ? 'bad-health' : 'unknown-health') %}

                    <a href="{{ path('show.mediaList', {id: playlist.id}) }}" class="table-link">
                        {{ playlist.lastUpdateResult }}
                        <button class="pill-button {{ healthClass }}"></button>
                    </a>
                </td>
                <td><a href="{{ path('show.mediaList', {id: playlist.id}) }}" class="table-link">{{ playlist.title }}</a></td>
                <td><a href="{{ path('show.mediaList', {id: playlist.id}) }}" class="table-link">{{ playlist.url }}</a></td>
                <td><a href="{{ path('show.mediaList', {id: playlist.id}) }}" class="table-link">{{ playlist.cronjob }}</a></td>
                <td><a href="{{ path('show.mediaList', {id: playlist.id}) }}" class="table-link">{{ playlist.deleteAfter > 0 ? playlist.deleteAfter ~ ' jours' : 'Infini' }}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <hr>
    <h3>Chaînes {{ archive is defined ? ' archivées' : '' }}</h3>
    <div class="table-container">
        <table>
            <colgroup>
                <col style="width: 4%;"> <!-- Première colonne -->
                <col style="width: 30%;"> <!-- Deuxième colonne -->
                <col style="width: 35%;"> <!-- Troisième colonne -->
                <col style="width: 15%;"> <!-- Quatrième colonne -->
                <col style="width: 15%;"> <!-- Cinquième colonne -->
            </colgroup>
            <thead>
            <tr>
                <th class="index-th-poster"></th>
                <th>Nom</th>
                <th>URL</th>
                <th>Cronjob</th>
                <th>Age Max</th>
            </tr>
            </thead>
            <tbody>
            {% for channel in channels %}
                <tr>
                    <td class="index-th-poster"><a href="{{ path('show.mediaList', {id: channel.id}) }}" class="table-link">
                            <img src="{{ asset('downloaded/posters/' ~ channel.title ~ '.jpg') }}"
                                 onerror="this.onerror=null; this.src='{{ asset('downloaded/default-poster.jpg') }}';"
                                 class="mediaList-poster"
                                 style="max-width: 100px;"
                                 alt="Poster de {{ channel.title }}"/>
                        </a>
                    </td>
                    <td><a href="{{ path('show.mediaList', {id: channel.id}) }}" class="table-link">{{ channel.title }}</a></td>
                    <td><a href="{{ path('show.mediaList', {id: channel.id}) }}" class="table-link">{{ channel.url }}</a></td>
                    <td><a href="{{ path('show.mediaList', {id: channel.id}) }}" class="table-link">{{ channel.cronjob }}</a></td>
                    <td><a href="{{ path('show.mediaList', {id: channel.id}) }}" class="table-link">{{ channel.deleteAfter > 0 ? channel.deleteAfter ~ ' jours' : 'Infini' }}</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/mediaList.html.twig
{% extends 'base.html.twig' %}

{% if mediaList.archived == true %}
    {% set title %}
        {{ mediaList.title }}<span style="font-size:.75em">, {{ mediaList.type == 0 ? 'playlist ' : 'chaîne ' }} archivée</span>
    {% endset %}
{% else %}
    {% set title %}
        {{ mediaList.title }}<span style="font-size:.75em">, {{ mediaList.type == 0 ? 'playlist ' : 'chaîne ' }} active</span>
    {% endset %}
{% endif %}

{% set page_title %} {{ mediaList.title }}{% endset %}
{% block title %} {{ title }}{% endblock %}

{% block body %}

    <h2>{{ title }}</h2>

    {% if mediaList is not empty %}

        <div class="mediaList-container">
            <div class="mediaList-poster-container">
                <img src="{{ asset('downloaded/posters/' ~ mediaList.title ~ '.jpg') }}"
                     onerror="this.onerror=null; this.src='{{ asset('downloaded/default-poster.jpg') }}';"
                     class="mediaList-poster mediaList-poster-shadowed"
                     alt="Poster de {{ mediaList.title }}"
                />
                {% set healthClass = mediaList.lastUpdateResult is same as(true)
                    ? 'good-health'
                    : (mediaList.lastUpdateResult is same as(false) ? 'bad-health' : 'unknown-health') %}

                {% set healthText = mediaList.lastUpdateResult is same as(true)
                    ? 'GOOD'
                    : (mediaList.lastUpdateResult is same as(false) ? 'BAD' : 'UNKNOWN') %}

                <button class="pill-button {{ healthClass }}">
                    {{ healthText }} HEALTH
                </button>
            </div>
            <div>
                <h3>Caractéristiques :</h3>
                <ul class="carac-sett-list">
                    <li>Url : <a href="{{ mediaList.url }}" target="_blank">{{ mediaList.url }}</a>&#8599;</li>
                    <li>Contient {{ mediaList.totalVideos }} vidéo{{ mediaList.totalVideos > 1 ? 's' : '' }}</li>
                    <li>{{ mediaList.downloadedVideos }} vidéos ont été téléchargées</li>
                    <li>{{ mediaList.deletedVideos }} vidéos ont été supprimées</li>
                    <li>Dernier scan :
                        {{ mediaList.updatedAt is empty
                        ? 'jamais fait'
                        : 'le ' ~ mediaList.updatedAt|date("j F Y à H\\hi") ~
                        (mediaList.lastUpdateResult == true ? ' avec succès' : ' mais a échoué !')
                        }}
                    </li>
                </ul>
                <h3>Réglages :</h3>
                <ul class="carac-sett-list">
                    <li>Téléchargement des {{ mediaList.xLastVideos }} dernières vidéos</li>
                    <li>
                        {{ mediaList.deleteAfter > 0 ? mediaList.deleteAfter > 1 ? 'Supprimer les vidéos téléchargées après ' ~ mediaList.deleteAfter ~ ' jours' : 'Supprimer les vidéos téléchargées après ' ~ mediaList.deleteAfter ~ ' jour' : 'Les vidéos ne sont jamais supprimées' }}
                    </li>
                    <li>Cronjob : {{ mediaList.cronjob }}</li>
                    <li>Qualité : {{ mediaList.quality > 0 ? mediaList.quality ~ '/3' : 'Audio seulement' }}</li>
                    <li>Chemin de téléchargement : {{ mediaList.path }}</li>
                </ul>
                <p>
                    <a href="#" class="button download-button">Scanner</a>
                    <a href="{{ path('edit.mediaList', {id: mediaList.id}) }}" class="button edit-button">Modifier</a>
                    <a href="{{ path('arch.mediaList', {id: mediaList.id}) }}" class="button arch-button" id="arch-button">{{  mediaList.archived == 'true' ? 'Activer' : 'Archiver' }}</a>
                    <a href="{{ path('delete.mediaList', {id: mediaList.id}) }}" class="button del-button" id="del-button">Supprimer</a>
                </p>
                <p style="margin-top:4em">
                    <a href="{{  mediaList.archived == 'true' ? path('index.archived') : path('index') }}" class="button add-button">Revenir {{ mediaList.archived == 'true' ? 'aux archives' : 'à l\'index' }}</a>
                </p>
            </div>
        </div>


        <!-- Modales -->
        <div id="confirm-popup-arch" class="popup-overlay" style="display: none;">
            <div class="popup-content">
                <p>Confirmer {{ mediaList.archived == 'true' ? 'l\'activation' : 'l\'archivage' }} ?</p>
                <button id="arch-yes" class="button">Oui</button>
                <button id="arch-no" class="button">Non</button>
            </div>
        </div>

        <div id="confirm-popup-delete" class="popup-overlay" style="display: none;">
            <div class="popup-content">
                <p>Confirmer la suppression ?</p>
                <button id="delete-yes" class="button">Oui</button>
                <button id="delete-no" class="button">Non</button>
            </div>
        </div>

        <script>
            // Modale Archivage
            document.addEventListener("DOMContentLoaded", function() {
                const archButton = document.getElementById('arch-button');
                const popupArch = document.getElementById('confirm-popup-arch');
                const archYes = document.getElementById('arch-yes');
                const archNo = document.getElementById('arch-no');

                archButton.addEventListener('click', function(event) {
                    event.preventDefault(); // Empêche le lien par défaut
                    popupArch.style.display = 'flex';
                });

                archYes.addEventListener('click', function() {
                    // Rediriger ou exécuter une action ici
                    window.location.href = archButton.href; // Exemple pour suivre le lien
                });

                archNo.addEventListener('click', function() {
                    popupArch.style.display = 'none'; // Cache la popup
                });
            });

            // Modale Delete
            document.addEventListener("DOMContentLoaded", function() {
                const delButton = document.getElementById('del-button');
                const popupDelete = document.getElementById('confirm-popup-delete');
                const deleteYes = document.getElementById('delete-yes');
                const deleteNo = document.getElementById('delete-no');

                delButton.addEventListener('click', function(event) {
                    event.preventDefault(); // Empêche le lien par défaut
                    popupDelete.style.display = 'flex';
                });

                deleteYes.addEventListener('click', function() {
                    // Rediriger ou exécuter une action ici
                    window.location.href = delButton.href; // Exemple pour suivre le lien
                });

                deleteNo.addEventListener('click', function() {
                    popupDelete.style.display = 'none'; // Cache la popup
                });
            });
        </script>



    {% else %}
        <p>Vide</p>
    {% endif %}

{% endblock %}